.TH HTTPSSL 8 "Feb. 2003" "Thomas M. Ogrisegg" "cthulhu webserver"

.\"* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
.\"Copyright (C) 2002, 2003 Thomas M. Ogrisegg. All rights reserved
.\"* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

.SH NAME
http-ssl -- SSL support for the Cthulhu HTTP daemon
.SH SYNOPSIS
ipinit http-ssl -m <number> [-f certificate file] [-p port] [-h address]
.SH DESCRIPTION
http-ssl implements simple SSL forwarding. It listens on an INTERNET socket
for incoming connections, forks and then forwards data packets in both
directions.

It is strongly recommended to run http-ssl in a chroot environment, as the
OpenSSL library with which it performs the SSL encryption/decryption is
generally considered insecure.

http-ssl is best started via an
.BR ipinit (8)
script

.SH OPTIONS
.TP 12
.B -f
this option let's you specify a different SSL certificate file (default:
http-ssl.pem)
.TP 12
.B -p
destination port. Specifies the port to which http-ssl should connect on
incoming connections (default: 80)
.TP 12
.B -h
IPv4 Address. Specifies to which address http-ssl should connect on incoming
connections (default: 127.0.0.1)
.TP 12
.B -m
maximum number of simultaenous clients. http-ssl will not accept more than
128 simultaneous clients. The default setting is 0, so you will have to set
this.

.SH AUTHOR
http-ssl was developed by Thomas M. Ogrisegg <tom-cthulhu@fnord.at>

.SH SEE ALSO
.BR ipinit (8),
.BR cthulhu (8)
