/* winmine2.c */
int main(int n, char *cmd[]);
void show_issue(void);
void winmine(void);
int num_mine_beside(int x1, int y1);
int num_mark_beside(int x1, int y1);
void wininit(int x1, int y1);
void dblclick(int x, int y);
void windig(int x, int y);
void winsh(int x, int y);
void winsh0(int x, int y);
void winloop(void);
int checkwin(void);
void dig(int x, int y);
int num_untouched_beside(int x, int y);
void windig2(int x, int y);
void winrefresh(void);
void winhelp(void);
void win_loadrec(void);
void win_saverec(void);
void win_showrec(void);
void win_checkrec(int dt);
void win_sort(void);
void clear(void);
void refresh(void);
void prints(char *b);
void move(int x, int y);
int egetch(void);
int getch0(void);
void quit(void);
void pressanykey(void);
void clearbuf(void);
void winmine2log(char *cc);
