/* tetris.c */
int get_tty(void);
void init_tty(void);
void reset_tty(void);
int getch(void);
int getch0(void);
void prints(char *s);
void oflush(void);
void move(int y1, int x1);
void color(int c);
void clear(void);
void clear2(void);
void sh2(void);
void sh(int y, int x, int k, int n, int c);
void show0(void);
int main(int argc, char *argv[]);
void quit(void);
void init_data(void);
int crash2(int x, int y, int k, int n);
void bell(void);
void start(void);
void down(void);
void checklines(void);
void tetrislog(char *cc);
void intr(void);
int count(void);
void win_loadrec(void);
void win_saverec(void);
void win_showrec(void);
void win_checkrec(int dt);
void win_sort(void);
void presskey(void);
