OBJS = main.o alloc.o env.o config.o w.o hash.o
LINKFILE = w.c hash.c
TARGET = cgi-exec

all: $(TARGET)

$(TARGET): $(OBJS)
	 $(LD) $(LDFLAGS) $(OBJS) -o $(TARGET)

$(LINKFILE):
	ln -s ../../$@ $@

install:
	install $(TARGET) $(BASEDIR)/bin

clean:
	rm -f $(OBJS) $(TARGET) $(LINKFILE)
