/* station.c */
void report(char *s);
int is_valid_chatid(char *id);
int Isspace(int ch);
char *nextword(char **str);
int chatid_to_indx(int unum, char *chatid);
int fuzzy_chatid_to_indx(int unum, char *chatid);
int roomid_to_indx(char *roomid);
void do_send(fd_set *writefds, char *str);
void send_to_room(int room, char *str);
void send_to_unum(int unum, char *str);
void exit_room(int unum, int disp, char *msg);
void chat_topic(int unum, char *msg);
int enter_room(int unum, char *room, char *msg);
void logout_user(int unum);
int print_user_counts(int unum);
int login_user(int unum, char *msg);
void chat_list_rooms(int unum, char *msg);
int chat_do_user_list(int unum, char *msg, int whichroom);
void chat_list_by_room(int unum, char *msg);
void chat_list_users(int unum, char *msg);
void chat_map_chatids(int unum, int whichroom);
void chat_map_chatids_thisroom(int unum, char *msg);
void chat_setroom(int unum, char *msg);
void chat_nick(int unum, char *msg);
void chat_private(int unum, char *msg);
void put_chatid(int unum, char *str);
int chat_allmsg(int unum, char *msg);
void chat_act(int unum, char *msg);
void chat_cloak(int unum, char *msg);
void chat_join(int unum, char *msg);
void chat_kick(int unum, char *msg);
void chat_makeop(int unum, char *msg);
void chat_clear_ops(int unum);
int chat_unset_op(int unum, int recunum);
int chat_get_op(int rnum);
void chat_knock_room(int unum, char *msg);
void chat_clear_op(int unum, char *msg);
void chat_invite(int unum, char *msg);
void chat_broadcast(int unum, char *msg);
void chat_goodbye(int unum, char *msg);
int party_action(int unum, char *cmd, char *party);
int speak_action(int unum, char *cmd, char *msg);
int condition_action(int unum, char *cmd);
void view_action_verb(int unum);
int command_execute(int unum);
int process_chat_command(int unum);
int main(int argc, char *argv[]);
